### ISSUE TITLE
Download updates part 2

### ISSUE THREAD

**Issue by sophiathirza** [nbnuk/nbnatlas-issues#538]
1. Page refresh to show download link once completed  (#536 )
2. Life-stage populating (upload new biocache program and reindex)
3. Simplify headers file to only include 3 columns
4. add occurrenceStatus and coordinateUncertaintyInMeters to full DwC dowload  (#353)
5. add end date, end month and end year to simple download
6. add rank back to the simple download, so that it is easy to identify hybrids, aggregates, varieties etc.

**Comment by sophiathirza** [comment]
End date has been added to the simple download but can end month and end year be included as well?

When you download this record: https://records.nbnatlas.org/occurrences/ff4f626d-1787-4517-8279-120068383bbd/, which has a year range, the end date is empty.

**Comment by sophiathirza** [comment]
The priority for these is:

- [x] 1. add end month, end year and rank to simple download
- [x] 2. add new download reason (#610)
- [x] 3. add occurrenceStatus and coordinateUncertaintyInMeters to full DwC dowload (#353)
- [x] 4. Page refresh to show download link once completed (#536 )
- [x] 5. Life-stage populating
- [x] 6. Simplify headers file to only include 3 columns

**Comment by reupost** [comment]
This should be ok now, except (4) I haven't done yet.

**Comment by sophiathirza** [comment]
did you do (2)? I can't see LERC as a download reason.

**Comment by reupost** [comment]
Whoops, no not yet, sorry.

**Comment by sophiathirza** [comment]
1, 3, 5 and 6 are perfect - thanks!

**Comment by reupost** [comment]
(2) done

**Comment by reupost** [comment]
Page refresh done

**Comment by sophiathirza** [comment]
Brilliant - thanks. All done.
